// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: links.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links (id , link , created_at) VALUES ($1 , $2, $3)
RETURNING id, link, created_at
`

type CreateLinkParams struct {
	ID        uuid.UUID
	Link      string
	CreatedAt sql.NullTime
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRowContext(ctx, createLink, arg.ID, arg.Link, arg.CreatedAt)
	var i Link
	err := row.Scan(&i.ID, &i.Link, &i.CreatedAt)
	return i, err
}

const listLinksById = `-- name: ListLinksById :many
SELECT id, link, created_at FROM links WHERE id = $1
`

func (q *Queries) ListLinksById(ctx context.Context, id uuid.UUID) ([]Link, error) {
	rows, err := q.db.QueryContext(ctx, listLinksById, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(&i.ID, &i.Link, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinksByLink = `-- name: ListLinksByLink :many
SELECT id, link, created_at FROM links WHERE link = $1
`

func (q *Queries) ListLinksByLink(ctx context.Context, link string) ([]Link, error) {
	rows, err := q.db.QueryContext(ctx, listLinksByLink, link)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(&i.ID, &i.Link, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
