// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: links.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links (id , link , created_at) VALUES ($1 , $2, $3)
RETURNING id, link, created_at
`

type CreateLinkParams struct {
	ID        uuid.UUID
	Link      string
	CreatedAt sql.NullTime
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRowContext(ctx, createLink, arg.ID, arg.Link, arg.CreatedAt)
	var i Link
	err := row.Scan(&i.ID, &i.Link, &i.CreatedAt)
	return i, err
}
