// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: links.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links (id , link , short_link , created_at) VALUES ($1 , $2, $3 ,$4)
RETURNING id, link, short_link, created_at
`

type CreateLinkParams struct {
	ID        uuid.UUID
	Link      string
	ShortLink string
	CreatedAt time.Time
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRowContext(ctx, createLink,
		arg.ID,
		arg.Link,
		arg.ShortLink,
		arg.CreatedAt,
	)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Link,
		&i.ShortLink,
		&i.CreatedAt,
	)
	return i, err
}

const getLinkById = `-- name: GetLinkById :one
SELECT id, link, short_link, created_at FROM links WHERE id = $1
`

func (q *Queries) GetLinkById(ctx context.Context, id uuid.UUID) (Link, error) {
	row := q.db.QueryRowContext(ctx, getLinkById, id)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Link,
		&i.ShortLink,
		&i.CreatedAt,
	)
	return i, err
}

const listLinks = `-- name: ListLinks :many
SELECT id, link, short_link, created_at FROM links
`

func (q *Queries) ListLinks(ctx context.Context) ([]Link, error) {
	rows, err := q.db.QueryContext(ctx, listLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.Link,
			&i.ShortLink,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinksByLink = `-- name: ListLinksByLink :one
SELECT id, link, short_link, created_at FROM links WHERE short_link = $1
`

func (q *Queries) ListLinksByLink(ctx context.Context, shortLink string) (Link, error) {
	row := q.db.QueryRowContext(ctx, listLinksByLink, shortLink)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Link,
		&i.ShortLink,
		&i.CreatedAt,
	)
	return i, err
}
