// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type Link struct {
	ID        int64
	Link      string
	GenKey    sql.NullString
	CreatedAt time.Time
}
