// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Link struct {
	ID           int64
	ShortLink    string
	OriginalLink string
	UserID       int64
	CreatedAt    time.Time
}

type User struct {
	ID        int64
	Name      string
	Email     sql.NullString
	CreatedAt time.Time
}
