// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Link struct {
	ID           uuid.UUID
	ShortLink    string
	OriginalLink string
	UserID       uuid.UUID
	CreatedAt    time.Time
}

type Otp struct {
	ID        uuid.UUID
	Otp       string
	UserID    uuid.UUID
	ExpAt     time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type RefreshToken struct {
	ID        uuid.UUID
	ExpDate   time.Time
	Token     string
	UserID    uuid.UUID
	CreatedAt time.Time
}

type User struct {
	ID         uuid.UUID
	Name       string
	Email      sql.NullString
	Password   sql.NullString
	IsVerified sql.NullBool
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
