// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (id , exp_date,token ,user_id , created_at) VALUES ($1 , $2, $3 ,$4,$5)
RETURNING id, exp_date, token, user_id, created_at
`

type CreateRefreshTokenParams struct {
	ID        uuid.UUID
	ExpDate   time.Time
	Token     string
	UserID    uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createRefreshToken,
		arg.ID,
		arg.ExpDate,
		arg.Token,
		arg.UserID,
		arg.CreatedAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.ExpDate,
		&i.Token,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
DELETE FROM refresh_tokens WHERE user_id=$1
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRefreshToken, userID)
	return err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, exp_date, token, user_id, created_at FROM refresh_tokens WHERE user_id=$1
`

func (q *Queries) GetRefreshToken(ctx context.Context, userID uuid.UUID) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshToken, userID)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.ExpDate,
		&i.Token,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}
