definitions:
  handler.CreateUserRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
info:
  contact: {}
  description: This is a server that give short url.
  license:
    name: Apache 2.0
  title: Swagger AchirURL API
  version: "1.0"
paths:
  /v1/users:
    post:
      consumes:
      - application/json
      description: Create a new user account
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/handler.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
      summary: Create a user
      tags:
      - users
swagger: "2.0"
